source 'https://github.com/CocoaPods/Specs.git'

target 'MWPhotoBrowser_Example' do
    pod 'KSMWPhotoBrowser', :path => '../'
    pod 'SDWebImage'
end

target 'MWPhotoBrowser_Tests' do
    use_frameworks!
    pod 'KSMWPhotoBrowser', :path => '../'
    
    pod 'SDWebImage'
    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
end
